FROM alpine:3.24 AS builder
RUN apk add --no-cache gcc musl-dev nng-dev

COPY proxy/proxy.c /src/
COPY runtime/actor_tuple.h /src/
COPY runtime/actor_uuid.h /src/
WORKDIR /src
RUN gcc -Wall -Wextra -Os -std=c11 proxy.c -lnng -o /mesh-proxy && \
    strip /mesh-proxy

FROM alpine:3.24
RUN apk add --no-cache nng
COPY --from=builder /mesh-proxy /
EXPOSE 5556 5557 8082
ENTRYPOINT ["/mesh-proxy"]
